//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGameServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Turn = new HashSet<Turn>();
        }
    
        public int id_game { get; set; }
        public int id_initiator { get; set; }
        public Nullable<int> id_challenger { get; set; }
        public int phrase { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> winner { get; set; }
        public int game_status { get; set; }
        public int game_language { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual GameLanguage GameLanguage { get; set; }
        public virtual Phrase Phrase1 { get; set; }
        public virtual GameStatus GameStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turn> Turn { get; set; }
    }
}
