//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGameServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phrase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phrase()
        {
            this.Game = new HashSet<Game>();
        }
    
        public int id_phrase { get; set; }
        public int id_category { get; set; }
        public string phrase_english { get; set; }
        public string hint_english { get; set; }
        public string phrase_spanish { get; set; }
        public string hint_spanish { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game> Game { get; set; }
    }
}
