//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanGameServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turn
    {
        public int id_turn { get; set; }
        public int id_game { get; set; }
        public string word { get; set; }
        public int remaining_attempts { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
